/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/banners/Banner.vue')['default']
    Banner404: typeof import('./src/components/banners/Banner404.vue')['default']
    BannerComingSoon: typeof import('./src/components/banners/BannerComingSoon.vue')['default']
    BannerTwo: typeof import('./src/components/banners/BannerTwo.vue')['default']
    BaseIcon: typeof import('./src/components/icons/BaseIcon.vue')['default']
    ChevronIcon: typeof import('./src/components/icons/ChevronIcon.vue')['default']
    ComingSoonBanner: typeof import('./src/components/banners/ComingSoonBanner.vue')['default']
    copy: typeof import('./src/components/cards/EventCards copy.vue')['default']
    EventCards: typeof import('./src/components/cards/EventCards.vue')['default']
    GlobeIcon: typeof import('./src/components/icons/GlobeIcon.vue')['default']
    GlobeRBCN: typeof import('./src/components/icons/GlobeRBCN.vue')['default']
    LinkIcon: typeof import('./src/components/icons/LinkIcon.vue')['default']
    LocaleToggler: typeof import('./src/components/blocks/LocaleToggler.vue')['default']
    Logo: typeof import('./src/components/blocks/Logo.vue')['default']
    MainBanner: typeof import('./src/components/banners/custom/MainBanner.vue')['default']
    Navbar: typeof import('./src/components/navigation/Navbar.vue')['default']
    NavMobile: typeof import('./src/components/NavMobile.vue')['default']
    NewsBanner: typeof import('./src/components/NewsBanner.vue')['default']
    NewTabIcon: typeof import('./src/components/icons/NewTabIcon.vue')['default']
    NotFoundBanner: typeof import('./src/components/banners/NotFoundBanner.vue')['default']
    NotFouondBanner: typeof import('./src/components/banners/NotFouondBanner.vue')['default']
    PageFooter: typeof import('./src/components/footer/PageFooter.vue')['default']
    PageSection: typeof import('./src/components/sections/PageSection.vue')['default']
    PreviousTalks: typeof import('./src/components/PreviousTalks.vue')['default']
    RobotIcon: typeof import('./src/components/icons/RobotIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/blocks/Settings.vue')['default']
    SpeakerCards: typeof import('./src/components/cards/SpeakerCards.vue')['default']
    SponsorCards: typeof import('./src/components/cards/SponsorCards.vue')['default']
    SponsorGrid: typeof import('./src/components/cards/SponsorGrid.vue')['default']
    SponsorItem: typeof import('./src/components/SponsorItem.vue')['default']
    Sponsors: typeof import('./src/components/Sponsors.vue')['default']
    TabBox: typeof import('./src/components/TabBox.vue')['default']
    Talks: typeof import('./src/components/Talks.vue')['default']
    Talks2023: typeof import('./src/components/Talks2023.vue')['default']
    Talks24: typeof import('./src/components/Talks24.vue')['default']
    ThemeToggler: typeof import('./src/components/blocks/ThemeToggler.vue')['default']
    TicketItem: typeof import('./src/components/TicketItem.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    ToggleDirection: typeof import('./src/components/blocks/ToggleDirection.vue')['default']
    Tutorials24: typeof import('./src/components/Tutorials24.vue')['default']
    Workshops24: typeof import('./src/components/Workshops24.vue')['default']
  }
}
