/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseBanner: typeof import('./src/components/banners/custom/BaseBanner.vue')['default']
    BaseIcon: typeof import('./src/components/icons/BaseIcon.vue')['default']
    ChevronIcon: typeof import('./src/components/icons/ChevronIcon.vue')['default']
    ComingSoonBanner: typeof import('./src/components/banners/ComingSoonBanner.vue')['default']
    EventCard: typeof import('./src/components/cards/EventCard.vue')['default']
    GlobeIcon: typeof import('./src/components/icons/GlobeIcon.vue')['default']
    GlobeRBCN: typeof import('./src/components/icons/GlobeRBCN.vue')['default']
    InfiniteSpinner: typeof import('./src/components/spinners/InfiniteSpinner.vue')['default']
    LinkIcon: typeof import('./src/components/icons/LinkIcon.vue')['default']
    Logo: typeof import('./src/components/blocks/Logo.vue')['default']
    MainBanner: typeof import('./src/components/banners/custom/MainBanner.vue')['default']
    Navbar: typeof import('./src/components/navigation/Navbar.vue')['default']
    NewsBanner: typeof import('./src/components/NewsBanner.vue')['default']
    NewTabIcon: typeof import('./src/components/icons/NewTabIcon.vue')['default']
    NotFoundBanner: typeof import('./src/components/banners/NotFoundBanner.vue')['default']
    PageFooter: typeof import('./src/components/footer/PageFooter.vue')['default']
    PageSection: typeof import('./src/components/sections/PageSection.vue')['default']
    PreviousTalks: typeof import('./src/components/PreviousTalks.vue')['default']
    RobotIcon: typeof import('./src/components/icons/RobotIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeakerCards: typeof import('./src/components/cards/SpeakerCards.vue')['default']
    SponsorCard: typeof import('./src/components/cards/SponsorCard.vue')['default']
    SponsorItem: typeof import('./src/components/SponsorItem.vue')['default']
    Sponsors: typeof import('./src/components/Sponsors.vue')['default']
    TabBox: typeof import('./src/components/TabBox.vue')['default']
    Talks: typeof import('./src/components/Talks.vue')['default']
    Talks2023: typeof import('./src/components/Talks2023.vue')['default']
    Talks24: typeof import('./src/components/Talks24.vue')['default']
    TicketCard: typeof import('./src/components/tickets/TicketCard.vue')['default']
    TicketFeatures: typeof import('./src/components/tickets/TicketFeatures.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    Tutorials24: typeof import('./src/components/Tutorials24.vue')['default']
    Workshops24: typeof import('./src/components/Workshops24.vue')['default']
  }
}
